baseURL = 'https://www.caiyongji.com'
languageCode = 'en-us'
title = 'CAIYONGJI'
theme = "hextra"

[[menu.main]]
name = "首页"
url = "/"
weight = 10

[[menu.main]]
name = "博客"
url = "/blog/"
weight = 20

[[menu.main]]
name = "关于"
url = "/about/"
weight = 30
